/**
 * Generated runtime configuration for service: web (dev namespace)
 * Generated by: tsops prune web --namespace dev
 */

import { useConfig } from 'tsops'

export default useConfig({
  "project": "hyper-graph",
  "namespace": "dev",
  "service": {
    "name": "web",
    "kind": "gateway",
    "image": "ghcr.io/org/hyper-graph-web:abc123",
    "internalUrl": "http://hyper-graph-web.dev.svc.cluster.local:8080",
    "externalUrl": "https://dev.hyper-graph.com",
    "port": 8080,
    "resources": {
      "cpu": "100m",
      "memory": "128Mi",
      "replicas": 1
    }
  },
  "dependencies": [
    {
      "service": "api",
      "url": "http://hyper-graph-api.dev.svc.cluster.local:8080",
      "port": 8080,
      "protocol": "http",
      "description": "Main API service"
    },
    {
      "service": "auth",
      "url": "http://hyper-graph-auth.dev.svc.cluster.local:8081",
      "port": 8081,
      "protocol": "http",
      "description": "Authentication service"
    }
  ],
  "environment": {
    "NODE_ENV": {
      "type": "static",
      "value": "production"
    },
    "PORT": {
      "type": "static",
      "value": "8080"
    },
    "API_URL": {
      "type": "static",
      "value": "http://hyper-graph-api.dev.svc.cluster.local:8080"
    },
    "AUTH_URL": {
      "type": "static",
      "value": "http://hyper-graph-auth.dev.svc.cluster.local:8081"
    },
    "DOMAIN": {
      "type": "static",
      "value": "dev.hyper-graph.com"
    },
    "DEBUG": {
      "type": "static",
      "value": "true"
    },
    "LOG_LEVEL": {
      "type": "static",
      "value": "debug"
    },
    "REPLICAS": {
      "type": "static",
      "value": "1"
    }
  },
  "namespaceVars": {
    "domain": "dev.hyper-graph.com",
    "replicas": 1,
    "debug": true,
    "logLevel": "debug"
  }
})

// Example usage:
// const apiUrl = config.dependencyUrl('api')        // http://hyper-graph-api.dev.svc.cluster.local:8080
// const authUrl = config.dependencyUrl('auth')      // http://hyper-graph-auth.dev.svc.cluster.local:8081
// const domain = config.namespaceVar('domain')      // dev.hyper-graph.com
// const debug = config.namespaceVar('debug')        // true
// const logLevel = config.env('LOG_LEVEL')          // debug