name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag/branch) to publish from'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: false
    env:
      NODE_VERSION: '24'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build packages
        run: pnpm build

      - name: Prepare release notes (from CHANGELOG)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          node <<'NODE'
          const fs = require('fs');
          const version = process.env.VERSION;
          const text = fs.readFileSync('CHANGELOG.md','utf8');
          const esc = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
          const re1 = new RegExp('^## \\['+esc(version)+'\\]\\n([\\s\\S]*?)(?=^## \\[)','m');
          const re2 = new RegExp('^## \\['+esc(version)+'\\]\\n([\\s\\S]*)$','m');
          const m = text.match(re1) || text.match(re2);
          if (!m) { console.error('Release notes not found for '+version); process.exit(1); }
          fs.writeFileSync('RELEASE_NOTES.md', m[1].trim()+"\n");
          NODE
        env:
          VERSION: ${{ github.ref_name }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md

      - name: Verify tag matches CLI version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          CLI_VER=$(node -p "require('./packages/cli/package.json').version")
          if [ "$CLI_VER" != "$VERSION" ]; then
            echo "Tag $TAG does not match CLI version $CLI_VER" >&2
            exit 1
          fi

      - name: Publish packages to npm
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
