name: Version Packages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Create versions from changesets
        run: pnpm changeset:version
      - name: Commit and push version bumps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci: version packages" || echo "no changes"
          git push || echo "no changes"
      - name: Create tag for CLI
        run: |
          VER=$(node -p "require('./packages/cli/package.json').version")
          if [ -n "$VER" ]; then
            git tag -a "v$VER" -m "v$VER" || true
            git push origin "v$VER" || true
          fi
